[tool.poetry]
name = "shredmaster"
version = "0.0.1"
description = "Program to scrape routes from the Strava api + shred."
authors = ["0110110 <davidwhittingham@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"
# TODO: Upgrade to python3.10
requests = "^2.28.1"
geojson = "^2.5.0"
python-json-logger = "^2.0.4"
mypy = "^0.982"
ratelimit = "^2.2.1"
isort = "^5.10.1"
pylint = "^2.15.5"
polyline = "^1.4.0"
fal = "^0.7.1"
fastapi = "^0.85.1"
uvicorn = "^0.19.0"
psycopg = "^3.1.4"
dbt-postgres = "^1.3.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.982"
pytest = "^7.1.3"
sqlfluff = "^1.3.2"
types-requests = "^2.28.11.2"
sqlfluff-templater-dbt = "^1.3.2"
ratelimit-stubs = "^2.2.1"
codespell = "^2.2.2"
pandas-stubs = "^1.5.2.221213"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.sqlfluff.core]
templater = "dbt"
dialect = "postgres"

[tool.sqlfluff.templater.dbt]
project_dir = "lab"
profiles_dir = "lab"
profile = "lab"
target = "main"
templater = "dbt"
dialect = "postgres"

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true

[tool.pylint."messages control"]
disable = [
    "fixme",
    "missing-function-docstring",
    "logging-fstring-interpolation",
    "missing-module-docstring",
    "missing-class-docstring",
]


[tool.codespell]
ignore-words-list = "crate"
