baseURL = "www.shred2bohemia.com"
languageCode = "en-us"
theme = "graysx"
title = "Shred 2 Bohemia"
[[menu.main]]
URL = "#about"
name = "About"
weight = 1
[[menu.main]]
URL = "#checkpoints"
name = "Checkpoints"
weight = 2
[[menu.main]]
URL = "#signup"
name = "Signup"
weight = 3
[params]
address = "123 Arch B1W, GNU/Linux"
email = "hello@graysx.com"
facebook = "#"
favicon = "assets/favicon.png"
github = "https://github.com/akatiggerx04/graysx-hugo"
logo = "assets/img/logo.webp"
phone = "123456"
sbtoken = "TOKEN_HERE"
twitter = "#"
